apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ini
  namespace: monitoring
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana

data:
  grafana.ini: |
    [server]
    root_url = https://k8s-grafana.example.com
