---
apiVersion: networking.k8s.io/v1
kind: Ingress #alb
metadata:
  name: ingress-prometheus-operator-alertmanager
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: #your_list_subnet,
    # for creating record-set
    external-dns.alpha.kubernetes.io/hostname: k8s-alertmanager.example.com # give your domain name here
    #additional
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: #<your-cert>
    alb.ingress.kubernetes.io/ssl-policy: #<your-ssl>
spec:
  rules:
    - host: "k8s-alertmanager.example.com"
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: prometheus-operator-alertmanager
              port:
                number: 9093

