---
apiVersion: extensions/v1beta1
kind: Ingress #alb
metadata:
  name: ingress-grafana
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: #your_subnet,
    # Health Check Settings
    alb.ingress.kubernetes.io/healthcheck-path: /login

    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '10'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '3'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '3'
    # for creating record-set
    external-dns.alpha.kubernetes.io/hostname: 	k8s-grafana.example.com # give your domain name here
    #additional
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: #your-arn
    alb.ingress.kubernetes.io/ssl-policy: #your-ssl-olicy
spec:
  rules:
    - host: "k8s-grafana.example.com"
      http:
        paths:
          - path: /*
            backend:
              serviceName: grafana
              servicePort: 3000


